---
title: 07 EXCEPTIONS AND ASSERTIONS
subtitle: 
author: John Qu
date: 2020-05-28
slug: exceptions-and-assertions
tags:
- 
categories:
- MIT600
- ICPP booknotes
typora-root-url: ../../static
show_toc: yes
output: html_notebook
---



<div id="is-exception-rare" class="section level3">
<h3>Is “exception” rare?</h3>
<p>An “exception” is usually defined as “something that does not conform to the norm,” and is therefore somewhat rare. There is nothing rare about exceptions in Python. They are everywhere. Virtually every module in the standard Python library uses them, and Python itself will raise them in many different circumstances.</p>
<p>If you know that a line of code might raise an exception when executed, you should handle the exception. In a well-written program, unhandled exceptions should be the exception.</p>
</div>
<div id="handling-exceptions" class="section level2">
<h2>7.1 Handling Exceptions</h2>
<div id="what-is-the-function-that-has-be-generalized-to-ask-for-any-type-of-input" class="section level3">
<h3>What is the function that has be generalized to ask for any type of input?</h3>
<pre class="python"><code>def readVal(valType, requestMsg, errorMsg): 
    while True:
        val = input(requestMsg + &#39; &#39;)
        try:
            return(valType(val)) #convert str to valType before returning
        except ValueError:
            print(val, errorMsg)
            
readVal(int, &#39;Enter an integer:&#39;, &#39;is not an integer&#39;)</code></pre>
</div>
</div>
<div id="exceptions-as-a-control-flow-mechanism" class="section level2">
<h2>7.2 Exceptions as a Control Flow Mechanism</h2>
<div id="what-is-the-difference-in-dealing-with-function-with-error-in-different-programming-language" class="section level3">
<h3>What is the difference in dealing with function with “error” in different programming language?</h3>
<p>In many programming languages, the standard approach to dealing with er- rors is to have functions return a value (often something analogous to Python’s None) indicating that something has gone amiss. Each function invocation has to check whether that value has been returned. In Python, it is more usual to have a function raise an exception when it cannot produce a result that is consistent with the function’s specification.</p>
</div>
<div id="what-is-the-except-block-used-for" class="section level3">
<h3>What is the <code>except:</code> block used for?</h3>
<p>In principle, the second except block should never be entered, because the code invoking getRatios should respect the assumptions in the specification of getRatios. However, since checking these assumptions imposes only an insignificant computational burden, it is probably worth practicing defensive programming and checking anyway.</p>
</div>
<div id="how-is-raise-and-except-used" class="section level3">
<h3>How is <code>raise</code> and <code>except</code> used?</h3>
<pre class="python"><code>def getRatios(vect1, vect2):
    &quot;&quot;&quot; Assumes: vect1 and vect2 are equal length lists of numbers
        Returns: a list containing the meaningful values of vect1[i]/vect2[i]&quot;&quot;&quot;
    ratios = []
    for index in range(len(vect1)):
        try:
            ratios.append(vect1[index]/vect2[index])
        except ZeroDivisionError:
            ratios.append(float(&#39;nan&#39;)) #nan = Not a Number
        except:
            raise ValueError(&#39;getRatios called with bad arguments&#39;)
    return ratios</code></pre>
<pre class="python"><code>try:
    print(getRatios([1.0,2.0,7.0,6.0], [1.0,2.0,0.0,3.0]))     
    print(getRatios([], []))
    print(getRatios([1.0, 2.0], [3.0]))
except ValueError as msg: print(msg)</code></pre>
<pre><code>## [1.0, 1.0, nan, 2.0]
## []
## getRatios called with bad arguments</code></pre>
<pre class="python"><code>def getGrades(fname):
    try:
        gradesFile = open(fname, &#39;r&#39;) #open file for reading
    except IOError:
        raise ValueError(&#39;getGrades could not open &#39; + fname)
    grades = []
    for line in gradesFile:
        try:
            grades.append(float(line))
        except:
            raise ValueError(&#39;Unable to convert line to float&#39;)
    return grades</code></pre>
<pre class="python"><code>try:
    grades = getGrades(&#39;quiz1grades.txt&#39;)
    grades.sort()
    median = grades[len(grades)//2]
    print(&#39;Median grade is&#39;, median)
except ValueError as errorMsg:
    print(&#39;Whoops.&#39;, errorMsg)</code></pre>
<pre><code>## Whoops. getGrades could not open quiz1grades.txt</code></pre>
</div>
</div>
<div id="assertions" class="section level2">
<h2>7.3 Assertions</h2>
<div id="what-are-assert-statement-used-for" class="section level3">
<h3>What are <code>assert</code> statement used for?</h3>
<p>Assertions are a useful defensive programming tool. They can be used to confirm that the arguments to a function are of appropriate types.</p>
<p>They are also a useful debugging tool. The can be used, for example, to confirm that intermediate values have the expected values or that a function returns an acceptable value.</p>
</div>
</div>
